### PR TITLE
Prepare release.

### PR DESCRIPTION
**Pull request by mcmtroffaes**

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
@equaeghe @sdestercke Do either of you use pycddlib on Windows? If so I'd appreciate if you could give one of new Windows wheels a try before I go about releasing them:

* Python 2.7 32 bit: https://ci.appveyor.com/api/buildjobs/7x4tsl9kejf9l140/artifacts/dist/pycddlib-1.0.5a1-cp27-none-win32.whl
* Python 2.7 64 bit: https://ci.appveyor.com/api/buildjobs/asxda1l235045m0s/artifacts/dist/pycddlib-1.0.5a1-cp27-none-win_amd64.whl
* Python 3.3 32 bit: https://ci.appveyor.com/api/buildjobs/btacbhacs418kcrp/artifacts/dist/pycddlib-1.0.5a1-cp33-none-win32.whl
* Python 3.3 64 bit: https://ci.appveyor.com/api/buildjobs/k0evyhgaopmyl1tx/artifacts/dist/pycddlib-1.0.5a1-cp33-none-win_amd64.whl
* Python 3.4 32 bit: https://ci.appveyor.com/api/buildjobs/ollobyyacy8ks1bm/artifacts/dist/pycddlib-1.0.5a1-cp34-none-win32.whl
* Python 3.4 64 bit: https://ci.appveyor.com/api/buildjobs/gm77nalky990a61i/artifacts/dist/pycddlib-1.0.5a1-cp34-none-win_amd64.whl

**Comment by equaeghe** [comment]
No, sorry.

**Comment by sdestercke** [comment]
Also no here :/

**Comment by mcmtroffaes** [comment]
@equaeghe @sdestercke Thanks for the response. I'll hold off the release until I have access to a proper windows machine, or until someone else can do a real life test of the binaries.

**Comment by mcmtroffaes** [comment]
@stephane-caron Are you by any chance on windows? If so could you test one of the binary wheels? (They are linked in one of the posts above in this pull request.)

**Comment by stephane-caron** [comment]
Sorry, I only use Linux. If I spot a Windows pythoner I will send him here.

**Comment by mcmtroffaes** [comment]
I've now released this - crossing fingers for windows users.

**Pull request merged**
